package com.linushestermeyer.hmi.view;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.view.View;
import android.widget.ImageButton;

import androidx.appcompat.app.AppCompatActivity;
import androidx.constraintlayout.widget.ConstraintLayout;

import com.google.android.material.snackbar.Snackbar;
import com.linushestermeyer.hmi.R;

import com.linushestermeyer.hmi.network.Connection;
import com.linushestermeyer.hmi.network.IMessageReader;
import com.linushestermeyer.hmi.network.MessageHandler;
import com.linushestermeyer.hmi.util.Constants;

import Actions.GoAwayAction;
import Actions.TargetAction;
import Messages.IMessage;
import Messages.ServiceActionCommand;
import Messages.ServiceActionMessage;
import Messages.ServiceRegistrationMessage;
import Messages.SoftwareRegistrationMessage;


//Do i need this activity? The view of the caris provided by the OEM. The lines which are drawn could be generated by the Drivingtask (AI), so the CarBaseSystem does this
public class MainActivity extends AppCompatActivity implements IMessageReader {

    private Connection connection = null;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        //Initializes Network Communication
        //TODO: check, if a new Connection gets Passed when sending a Message from one of the activities
        connection = Connection.getInstance();
        if(!connection.isRunning()){
            connection.startConnection();
            connection.setMessageReader(this);
            MessageHandler.getInstance().setConnection(connection);
        }


        ImageButton home = findViewById(R.id.homeButton);
        home.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent(MainActivity.this, HomeActivity.class);
                startActivity(intent);
            }
        });

        //init Broadcast Receivers
    }

    @Override
    public void readSocket(IMessage msg) {
        //Views wechseln oder Notification geben je nach Art der Nachricht
        if(msg instanceof ServiceRegistrationMessage){
            Intent openOffer = new Intent(MainActivity.this, ActivityPresentOffer.class);
            openOffer.putExtra(Constants.SERVICE_REGISTRATION_MESSAGE,(ServiceRegistrationMessage)msg);
            startActivity(openOffer);
        }else if(msg instanceof SoftwareRegistrationMessage) {
            Intent openOffer = new Intent(MainActivity.this, ActivityPresentOffer.class);
            openOffer.putExtra(Constants.SOFTWARE_REGISTRATION_MESSAGE,(SoftwareRegistrationMessage)msg);
            startActivity(openOffer);
        }else if(msg instanceof ServiceActionCommand){
            //present to the driver, what the car is going to do/where it is going to go
            ServiceActionCommand cmd = (ServiceActionCommand) msg;
            ConstraintLayout layout = findViewById(R.id.layout);
            if(cmd.getAction() instanceof GoAwayAction){
                Snackbar snackbar = Snackbar
                        .make(layout, "See you next time!", Snackbar.LENGTH_LONG);
                snackbar.show();
            } else if(cmd.getAction() instanceof TargetAction){
                Snackbar snackbar = Snackbar
                        .make(layout, "Welcome to your new Parkinglot!", Snackbar.LENGTH_LONG);
                snackbar.show();
            }
            //Todo: show snackbar and evaluate Action conatined in ServiceActionCOmmand
            Log.e("Success","Car is driving to Parkinglot");
        }
        //else if msg instanceof SoftwareRegistrationMessage
    }


}
